// scripts/build-default-dict.ts
// Build-time generator: produces assets/default-dict.txt and src/default_dict_words.ts
// from the canonical data/tdict-*.txt source files.

import * as fs from "node:fs";
import * as path from "node:path";
import { serializeDictionary, parseDictionary } from "../src/dict_format";

const DATA_DIR = path.resolve(__dirname, "..", "data");
const ASSET_OUT = path.resolve(__dirname, "..", "assets", "default-dict.txt");
const TS_OUT = path.resolve(__dirname, "..", "src", "default_dict_words.ts");

function readWords(): string[] {
  const files = fs
    .readdirSync(DATA_DIR)
    .filter((f) => f.startsWith("tdict-") && f.endsWith(".txt"))
    .sort();

  const all: string[] = [];
  for (const f of files) {
    const txt = fs.readFileSync(path.join(DATA_DIR, f), "utf8");
    for (const raw of txt.split("\n")) {
      const seg = raw.endsWith("\r") ? raw.slice(0, -1) : raw;
      if (seg.length > 0) all.push(seg);
    }
  }

  // Match the runtime sortuniq used in src/dict.ts:
  // a.sort().filter((item, pos, arr) => !pos || item !== arr[pos - 1])
  return all.sort().filter((item, pos, arr) => !pos || item !== arr[pos - 1]);
}

function emitAsset(words: string[]): void {
  fs.mkdirSync(path.dirname(ASSET_OUT), { recursive: true });
  fs.writeFileSync(ASSET_OUT, serializeDictionary(words), { encoding: "utf8" });
}

function emitTs(words: string[]): void {
  const lines = words.map((w) => "  " + JSON.stringify(w) + ",").join("\n");
  const body =
    "// AUTO-GENERATED by scripts/build-default-dict.ts. Do not edit by hand.\n" +
    "// Source: data/tdict-*.txt\n" +
    "const DEFAULT_DICT_WORDS = [\n" +
    lines +
    "\n] as const;\n\n" +
    "export default DEFAULT_DICT_WORDS;\n";
  fs.writeFileSync(TS_OUT, body, { encoding: "utf8" });
}

function selfCheck(words: string[]): void {
  // Check 1: Parse the asset back and assert deep-equality with the in-memory array
  const assetContent = fs.readFileSync(ASSET_OUT, "utf8");
  const parsed = parseDictionary(assetContent);
  if (parsed.length !== words.length) {
    console.error(
      `Asset self-check failed: expected ${words.length} words, got ${parsed.length}`
    );
    process.exit(1);
  }
  for (let i = 0; i < words.length; i++) {
    if (parsed[i] !== words[i]) {
      console.error(
        `Asset self-check failed at index ${i}: expected ${JSON.stringify(words[i])}, got ${JSON.stringify(parsed[i])}`
      );
      process.exit(1);
    }
  }

  // Check 2: Require the just-written TS module and assert the same
  // Since we run under tsx, we can require the .ts file directly
  const tsModule = require(TS_OUT);
  const tsWords: readonly string[] = tsModule.default;
  if (tsWords.length !== words.length) {
    console.error(
      `TS module self-check failed: expected ${words.length} words, got ${tsWords.length}`
    );
    process.exit(1);
  }
  for (let i = 0; i < words.length; i++) {
    if (tsWords[i] !== words[i]) {
      console.error(
        `TS module self-check failed at index ${i}: expected ${JSON.stringify(words[i])}, got ${JSON.stringify(tsWords[i])}`
      );
      process.exit(1);
    }
  }
}

// Main
const words = readWords();
emitAsset(words);
emitTs(words);
console.log(
  `Wrote ${words.length} words to ${ASSET_OUT} and ${TS_OUT}`
);

selfCheck(words);
console.log("Self-check passed: asset and TS module match in-memory array.");
